name: Publish Release

on:
  # The build will be triggered when we publish a release
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    - uses: actions/checkout@v2

    - name: Install Node.js 💻
      uses: actions/setup-node@v2
      with:
        node-version: '12.x'
        registry-url: https://npm.pkg.github.com

    - name: Install dependencies 🔧
      run: npm install

    - name: Version ✅
      run: npm version --no-git-tag-version ${{ github.event.release.tag_name }}

    - name: Test 🧪
      run: npm test

    - name: Publish 📚
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}